import { BaseEntity } from './../../shared';

export class Post implements BaseEntity {
    constructor(
        public id?: number,
        public creationDate?: any,
        public publicationDate?: any,
        public headline?: string,
        public lead?: string,
        public bodytext?: any,
        public quote?: string,
        public conclusion?: string,
        public imageContentType?: string,
        public image?: any,
        public comments?: BaseEntity[],
        public topNews1?: BaseEntity,
        public topNews2?: BaseEntity,
        public topNews3?: BaseEntity,
        public topNews4?: BaseEntity,
        public topNews5?: BaseEntity,
        public latestNews1?: BaseEntity,
        public latestNews2?: BaseEntity,
        public latestNews3?: BaseEntity,
        public latestNews4?: BaseEntity,
        public latestNews5?: BaseEntity,
        public breakingNews1?: BaseEntity,
        public recentPosts1?: BaseEntity,
        public recentPosts2?: BaseEntity,
        public recentPosts3?: BaseEntity,
        public recentPosts4?: BaseEntity,
        public featuredArticles1?: BaseEntity,
        public featuredArticles2?: BaseEntity,
        public featuredArticles3?: BaseEntity,
        public featuredArticles4?: BaseEntity,
        public featuredArticles5?: BaseEntity,
        public featuredArticles6?: BaseEntity,
        public featuredArticles7?: BaseEntity,
        public featuredArticles8?: BaseEntity,
        public featuredArticles9?: BaseEntity,
        public featuredArticles10?: BaseEntity,
        public popularNews1?: BaseEntity,
        public popularNews2?: BaseEntity,
        public popularNews3?: BaseEntity,
        public popularNews4?: BaseEntity,
        public popularNews5?: BaseEntity,
        public popularNews6?: BaseEntity,
        public popularNews7?: BaseEntity,
        public popularNews8?: BaseEntity,
        public weeklyNews1?: BaseEntity,
        public weeklyNews2?: BaseEntity,
        public weeklyNews3?: BaseEntity,
        public weeklyNews4?: BaseEntity,
        public newsFeeds1?: BaseEntity,
        public newsFeeds2?: BaseEntity,
        public newsFeeds3?: BaseEntity,
        public newsFeeds4?: BaseEntity,
        public newsFeeds5?: BaseEntity,
        public newsFeeds6?: BaseEntity,
        public blog?: BaseEntity,
        public tags?: BaseEntity[],
        public topics?: BaseEntity[],
    ) {
    }
}
